namespace ArmadaBackend.Enums
{
    public enum CardCategory
    {
        CommanderRebel, 
        CommanderImperial, 
        CommanderGAR, 
        CommanderCIS, 
        DefensiveRetrofitOG, 
        DefensiveRetrofitPRE, 
        ExperimentalRetrofit,
        FleetCommandOG,
        FleetCommandPRE,
        FleetSupport,
        IonCannons,
        OffensiveRetrofit,
        OffensiveRetrofitGAR,
        OffensiveRetrofitCIS,
        Officer,
        OfficerRebel,
        OfficerImperial,
        OfficerGAR,
        OfficerCIS,
        Ordnance,
        SuperweaponImperial,
        SuperweaponRebel,
        SupportTeam,
        SupportTeamCIS,
        TitleRebel,
        TitleImperial,
        TitleGAR,
        TitleCIS,
        Turbolasers,
        TurbolasersPRE,
        WeapTeam, 
        WeaponsTeamAndOffensiveRetrofit
    }
}
