// <auto-generated />
using ArmadaBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ArmadaBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260729130603_ShipModified")]
    partial class ShipModified
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ArmadaBackend.Models.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FleetElementId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Point")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FleetElementId");

                    b.ToTable("Cards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = 30,
                            Description = "Can attack from the same hull zone twice...",
                            Name = "Gunnery Team",
                            Point = 7
                        },
                        new
                        {
                            Id = 3,
                            Category = 28,
                            Description = "While performing a Salvo attack, you may change 1 die to face a hit/crit ($\\text{A}/\\text{B}$) icon.",
                            Name = "DBY-827 Heavy Turbolasers",
                            Point = 3
                        },
                        new
                        {
                            Id = 4,
                            Category = 28,
                            Description = "While attacking, you may change 1 red die to face a hit ($\\text{A}$) icon.",
                            Name = "Dual Turbolaser Turrets",
                            Point = 5
                        },
                        new
                        {
                            Id = 5,
                            Category = 28,
                            Description = "While attacking, you may change 1 hit or crit icon to an accuracy icon.",
                            Name = "H9 Turbolasers",
                            Point = 8
                        },
                        new
                        {
                            Id = 6,
                            Category = 28,
                            Description = "While attacking a ship, if the defender uses the brace defense token, that token reduces the total damage by only 1 instead of halving it.",
                            Name = "Heavy Turbolaser Turrets",
                            Point = 6
                        },
                        new
                        {
                            Id = 7,
                            Category = 28,
                            Description = "While attacking, you may reroll 1 red die. During your first anti-squadron attack each activation, you may add 1 red die to your attack pool.",
                            Name = "Linked Turbolaser Towers",
                            Point = 7
                        },
                        new
                        {
                            Id = 8,
                            Category = 28,
                            Description = "While attacking a ship, if your current speed is less than the defender's current speed, you may add 1 blue die to your attack pool.",
                            Name = "Quad Battery Turrets",
                            Point = 5
                        },
                        new
                        {
                            Id = 9,
                            Category = 28,
                            Description = "While attacking a ship, if you have at least 1 accuracy icon, you may add 1 red die with a hit icon to your attack pool.",
                            Name = "Quad Turbolaser Cannons",
                            Point = 10
                        },
                        new
                        {
                            Id = 10,
                            Category = 28,
                            Description = "You cannot attack a ship more than once per activation. While attacking a ship, you may add 1 red die to your attack pool.",
                            Name = "Slaved Turrets",
                            Point = 6
                        },
                        new
                        {
                            Id = 11,
                            Category = 28,
                            Description = "While attacking a ship, if your attack originates from your forward or rear hull zone, you may add 1 red die to your attack pool.",
                            Name = "Spinal Armament",
                            Point = 9
                        },
                        new
                        {
                            Id = 12,
                            Category = 28,
                            Description = "During the attack step, you may spend 1 evade token to change 1 red die to a double-hit or crit icon.",
                            Name = "Turbolaser Reroute Circuits",
                            Point = 7
                        },
                        new
                        {
                            Id = 13,
                            Category = 28,
                            Description = "While attacking a ship, the defender can resolve only 1 redirect token effect to redirect damage to another hull zone.",
                            Name = "XI7 Turbolasers",
                            Point = 6
                        },
                        new
                        {
                            Id = 14,
                            Category = 28,
                            Description = "While attacking a ship, if you deal a critical hit, the defender is dealt the first 2 damage cards of that attack faceup.",
                            Name = "XX-9 Turbolasers",
                            Point = 5
                        },
                        new
                        {
                            Id = 15,
                            Category = 19,
                            Description = "Black crit effect: Deal 1 faceup damage card to the defender before damage is resolved.",
                            Name = "Assault Proton Torpedoes",
                            Point = 5
                        },
                        new
                        {
                            Id = 16,
                            Category = 19,
                            Description = "Black crit effect: The hull zone adjacent to the defending hull zone suffers 1 damage.",
                            Name = "Concussion Missiles",
                            Point = 4
                        },
                        new
                        {
                            Id = 17,
                            Category = 19,
                            Description = "You may add 2 black dice to your forward battery armament.",
                            Name = "Expanded Launchers",
                            Point = 13
                        },
                        new
                        {
                            Id = 18,
                            Category = 19,
                            Description = "While attacking a ship at close range, you may discard this card to add 2 black dice to your attack pool.",
                            Name = "External Racks",
                            Point = 4
                        },
                        new
                        {
                            Id = 19,
                            Category = 19,
                            Description = "While attacking a squadron, if you roll a crit icon, flip the defender's activation slider.",
                            Name = "Flechette Torpedoes",
                            Point = 3
                        },
                        new
                        {
                            Id = 20,
                            Category = 19,
                            Description = "Medium or large ship only. At the end of your attack step, you may exhaust this card and choose 1 of your hull zones. Then perform an attack from that hull zone with an anti-squadron armament of 1 black die.",
                            Name = "Ordnance Pods",
                            Point = 3
                        },
                        new
                        {
                            Id = 21,
                            Category = 19,
                            Description = "You may add 1 black die to your left and right battery armaments.",
                            Name = "Rapid Reload",
                            Point = 8
                        },
                        new
                        {
                            Id = 22,
                            Category = 19,
                            Description = "Black crit effect: Choose another enemy ship or squadron at distance 1 of the defender. It suffers damage equal to half of the total black hit icons in the attack pool, rounded up.",
                            Name = "Wide-Area Barrage",
                            Point = 2
                        },
                        new
                        {
                            Id = 23,
                            Category = 10,
                            Description = "Blue crit effect: The defending hull zone and each adjacent hull zone lose 1 shield.",
                            Name = "Heavy Ion Emplacements",
                            Point = 9
                        },
                        new
                        {
                            Id = 24,
                            Category = 10,
                            Description = "You may add 1 blue die to your left and right battery armaments.",
                            Name = "High-Capacity Ion Turbines",
                            Point = 8
                        },
                        new
                        {
                            Id = 25,
                            Category = 10,
                            Description = "Blue crit effect: The defender either loses 1 shield from the defending hull zone or discards 1 of its command tokens.",
                            Name = "Ion Cannon Batteries",
                            Point = 5
                        },
                        new
                        {
                            Id = 26,
                            Category = 10,
                            Description = "While attacking a ship, you may discard 1 blue die from your attack pool to reroll any number of your other dice.",
                            Name = "Leading Shots",
                            Point = 6
                        },
                        new
                        {
                            Id = 27,
                            Category = 10,
                            Description = "Blue crit effect: Choose 1 upgrade card equipped to the defender; exhaust that card.",
                            Name = "MS-1 Ion Cannons",
                            Point = 2
                        },
                        new
                        {
                            Id = 28,
                            Category = 10,
                            Description = "Blue crit effect: The defender must discard 1 defense token instead of exhausting it.",
                            Name = "NK-7 Ion Cannons",
                            Point = 10
                        },
                        new
                        {
                            Id = 29,
                            Category = 10,
                            Description = "Blue crit effect: Exhaust each of the defender's defense tokens.",
                            Name = "Overload Pulse",
                            Point = 8
                        },
                        new
                        {
                            Id = 30,
                            Category = 10,
                            Description = "While attacking, you may treat your blue accuracy icons as hit icons.",
                            Name = "SW-7 Ion Batteries",
                            Point = 5
                        },
                        new
                        {
                            Id = 31,
                            Category = 14,
                            Description = "While defending, you can resolve a contain token to cancel standard critical effects.",
                            Name = "Damage Control Officer",
                            Point = 5
                        },
                        new
                        {
                            Id = 32,
                            Category = 14,
                            Description = "During the Command Phase, you may discard this card to place your top command dial on the bottom of your command stack.",
                            Name = "Skilled First Officer",
                            Point = 1
                        },
                        new
                        {
                            Id = 33,
                            Category = 14,
                            Description = "You may resolve a squadron command after your ship has moved instead of before it moves.",
                            Name = "Flight Commander",
                            Point = 3
                        },
                        new
                        {
                            Id = 34,
                            Category = 14,
                            Description = "During the Command Phase, you may discard this card to discard all of your command dials and replan.",
                            Name = "Support Officer",
                            Point = 4
                        },
                        new
                        {
                            Id = 35,
                            Category = 14,
                            Description = "While a friendly ship is spending a command token, it may treat that token as if it were a command dial.",
                            Name = "Leia Organa",
                            Point = 3
                        },
                        new
                        {
                            Id = 36,
                            Category = 14,
                            Description = "When your ship resolves a command from its dial, it gains a matching command token.",
                            Name = "Raymus Antilles",
                            Point = 7
                        },
                        new
                        {
                            Id = 37,
                            Category = 14,
                            Description = "While defending, you may discard this card to force the attacker to reroll all of their attack dice.",
                            Name = "Lando Calrissian",
                            Point = 4
                        },
                        new
                        {
                            Id = 38,
                            Category = 14,
                            Description = "While attacking at distance 1–3, friendly ships and squadrons may reroll 1 blue die.",
                            Name = "Toryn Farr",
                            Point = 7
                        },
                        new
                        {
                            Id = 39,
                            Category = 14,
                            Description = "When your ship activates, you may discard this card to ready 1 of your exhausted defense tokens.",
                            Name = "Walex Blissex",
                            Point = 5
                        },
                        new
                        {
                            Id = 40,
                            Category = 16,
                            Description = "During the ship placement phase, you may replace 1 of your defense tokens with an evade token.",
                            Name = "Captain Needa",
                            Point = 2
                        },
                        new
                        {
                            Id = 41,
                            Category = 16,
                            Description = "Your upgrade bar gains 1 defensive retrofit icon. Imperial ship only.",
                            Name = "Minister Tua",
                            Point = 2
                        },
                        new
                        {
                            Id = 42,
                            Category = 16,
                            Description = "While defending, you may exhaust this card and an obstacle at distance 1–2 to cancel 1 attack die.",
                            Name = "Captain Brunson",
                            Point = 5
                        },
                        new
                        {
                            Id = 43,
                            Category = 16,
                            Description = "While attacking, you may discard another upgrade card equipped to this ship to reroll any number of attack dice.",
                            Name = "Darth Vader (Officer)",
                            Point = 3
                        },
                        new
                        {
                            Id = 44,
                            Category = 16,
                            Description = "While resolving a squadron command, you may choose up to 2 engaged friendly squadrons; those squadrons can move as if they were not engaged, but cannot attack.",
                            Name = "Admiral Chiraneau",
                            Point = 10
                        },
                        new
                        {
                            Id = 45,
                            Category = 17,
                            Description = "You may discard this card to allow a friendly ship at distance 1–5 (or your ship) to activate +1 squadron this round.",
                            Name = "Clone Captain Rex",
                            Point = 5
                        },
                        new
                        {
                            Id = 46,
                            Category = 17,
                            Description = "When you spend a navigate token, you may choose a friendly ship at distance 1–5; it gains a navigate token.",
                            Name = "Clone Navigation Officer",
                            Point = 4
                        },
                        new
                        {
                            Id = 47,
                            Category = 17,
                            Description = "When you would spend a command token, you may exhaust this card to not discard that token.",
                            Name = "Admiral Yularen",
                            Point = 2
                        },
                        new
                        {
                            Id = 48,
                            Category = 17,
                            Description = "At the end of the ship placement phase, your left and right hull zones each gain 1 shield, up to their maximum values.",
                            Name = "Wat Tambor",
                            Point = 5
                        },
                        new
                        {
                            Id = 49,
                            Category = 18,
                            Description = "When another friendly ship at distance 1–5 reveals a command dial, you may gain a matching command token.",
                            Name = "Rune Haako",
                            Point = 4
                        },
                        new
                        {
                            Id = 50,
                            Category = 18,
                            Description = "At the beginning of the Command Phase, you may gain 1 concentrate fire token.",
                            Name = "San Hill",
                            Point = 3
                        },
                        new
                        {
                            Id = 51,
                            Category = 11,
                            Description = "While attacking, choose 1 defense token. If the defender spends that token during this attack, discard it instead of exhausting it.",
                            Name = "Intel Officer",
                            Point = 7
                        },
                        new
                        {
                            Id = 52,
                            Category = 18,
                            Description = "During the Command Phase, you may discard this card to gain 1 command token of your choice.",
                            Name = "Veteran Captain",
                            Point = 3
                        },
                        new
                        {
                            Id = 53,
                            Category = 18,
                            Description = "During setup, you gain a pass token. You may spend this token during the ship phase to pass your activation.",
                            Name = "Strategic Adviser",
                            Point = 16
                        },
                        new
                        {
                            Id = 54,
                            Category = 18,
                            Description = "You may exhaust this card to gain 2 different command tokens. Then, choose an enemy ship at distance 1–5; it gains 1 of those tokens.",
                            Name = "Hondo Ohnaka",
                            Point = 2
                        },
                        new
                        {
                            Id = 55,
                            Category = 18,
                            Description = "After you resolve a squadron command, you may exhaust this card to ready 1 friendly squadron you activated.",
                            Name = "Adar Tallon",
                            Point = 10
                        },
                        new
                        {
                            Id = 56,
                            Category = 14,
                            Description = "When you suffer damage from an attack, reduce the total damage suffered by 1 to a minimum of 1. Once per round.",
                            Name = "Major Derlin",
                            Point = 7
                        },
                        new
                        {
                            Id = 57,
                            Category = 14,
                            Description = "During the Command Phase, you may discard 1 command token to change your top command dial to any other command.",
                            Name = "Ahsoka Tano",
                            Point = 2
                        },
                        new
                        {
                            Id = 58,
                            Category = 14,
                            Description = "When you reveal a command dial, you may choose a command token you own. Treat that dial as if it were a matching command.",
                            Name = "Hera Syndulla (Officer)",
                            Point = 4
                        },
                        new
                        {
                            Id = 59,
                            Category = 14,
                            Description = "While attacking a ship at distance 1–3, you may assign 1 raid token to the defender.",
                            Name = "Jyn Erso",
                            Point = 4
                        },
                        new
                        {
                            Id = 60,
                            Category = 16,
                            Description = "At the start of the ship placement phase, you may choose an enemy ship and change its speed by 1 (to a minimum of 0 and a maximum of its max speed).",
                            Name = "Admiral Titus",
                            Point = 2
                        },
                        new
                        {
                            Id = 61,
                            Category = 16,
                            Description = "While attacking a unique squadron, you may add 1 red or black die to your anti-squadron attack pool.",
                            Name = "Agent Kallus",
                            Point = 3
                        },
                        new
                        {
                            Id = 62,
                            Category = 16,
                            Description = "When you execute a navigate command, you may change your speed by up to 1 beyond the normal restrictions.",
                            Name = "Captain Ozzel",
                            Point = 2
                        },
                        new
                        {
                            Id = 63,
                            Category = 18,
                            Description = "Friendly non-heavy squadrons at distance 1–2 of your ship gain counter 1.",
                            Name = "Instructor Goran",
                            Point = 7
                        },
                        new
                        {
                            Id = 64,
                            Category = 16,
                            Description = "At the start of the Command Phase, you may look at an enemy ship's command dials.",
                            Name = "Director Isard",
                            Point = 3
                        },
                        new
                        {
                            Id = 65,
                            Category = 16,
                            Description = "When you would spend a command token, you may exhaust this card to not discard that token.",
                            Name = "Wulff Yularen (Imperial)",
                            Point = 7
                        },
                        new
                        {
                            Id = 66,
                            Category = 17,
                            Description = "During the Command Phase, you may discard this card to give 1 command token of your choice to up to two other friendly ships at distance 1–5.",
                            Name = "Bail Organa (GAR)",
                            Point = 5
                        },
                        new
                        {
                            Id = 67,
                            Category = 17,
                            Description = "While your ship is attacking, you may exhaust this card and discard 1 concentrate fire token to reroll up to 2 attack dice.",
                            Name = "Clone Commander Wolffe",
                            Point = 5
                        },
                        new
                        {
                            Id = 68,
                            Category = 17,
                            Description = "Friendly squadrons at distance 1–3 of your ship force the attacker to reroll 1 attack die while defending.",
                            Name = "Aayla Secura",
                            Point = 5
                        },
                        new
                        {
                            Id = 69,
                            Category = 18,
                            Description = "While spending a command token, you may treat that token as if it were a command dial.",
                            Name = "T-Series Tactical Droid",
                            Point = 4
                        },
                        new
                        {
                            Id = 70,
                            Category = 18,
                            Description = "When you resolve a command (from a dial or token), you may gain 1 command token of a type different from that command.",
                            Name = "Passel Argente",
                            Point = 6
                        },
                        new
                        {
                            Id = 71,
                            Category = 18,
                            Description = "When you reveal a command dial that matches the command dial you revealed during the previous round, you may gain a matching command token.",
                            Name = "Tikkes",
                            Point = 2
                        },
                        new
                        {
                            Id = 72,
                            Category = 18,
                            Description = "While resolving a squadron command, 1 friendly squadron at distance 1–3 gains swarm until the end of the round.",
                            Name = "Poggle the Lesser",
                            Point = 3
                        },
                        new
                        {
                            Id = 73,
                            Category = 4,
                            Description = "While resolving a redirect token, you may distribute damage to any of your hull zones' shield tracks instead of just adjacent ones.",
                            Name = "Advanced Projectors",
                            Point = 6
                        },
                        new
                        {
                            Id = 74,
                            Category = 4,
                            Description = "While defending, you may exhaust this card to resolve a defense token even if it has been targeted by an accuracy icon.",
                            Name = "Electronic Countermeasures",
                            Point = 7
                        },
                        new
                        {
                            Id = 75,
                            Category = 4,
                            Description = "Choose 1 of your hull zones. Attacks targeting that hull zone are obstructed.",
                            Name = "Early Warning System",
                            Point = 7
                        },
                        new
                        {
                            Id = 76,
                            Category = 4,
                            Description = "During the Status Phase, you may recover 1 shield in any 1 hull zone.",
                            Name = "Redundant Shields",
                            Point = 8
                        },
                        new
                        {
                            Id = 77,
                            Category = 4,
                            Description = "You may discard this card to remove up to 3 facedown damage cards from your ship.",
                            Name = "Reinforced Blast Doors",
                            Point = 5
                        },
                        new
                        {
                            Id = 78,
                            Category = 4,
                            Description = "While defending, if you have a ready salvo token, you may discard another defense token to resolve a salvo attack as if you spent that salvo token.",
                            Name = "Reactive Gunnery",
                            Point = 4
                        },
                        new
                        {
                            Id = 79,
                            Category = 4,
                            Description = "While an enemy squadron attacks from distance 1, you may discard this card to roll 4 black dice against that squadron. Each hit deals 1 damage.",
                            Name = "Cluster Bombs",
                            Point = 5
                        },
                        new
                        {
                            Id = 80,
                            Category = 11,
                            Description = "Your squadron value is increased by 1.",
                            Name = "Expanded Hangar Bay",
                            Point = 5
                        },
                        new
                        {
                            Id = 81,
                            Category = 11,
                            Description = "When you resolve a squadron command, you may choose squadrons at distance 1–long instead of distance 1–3.",
                            Name = "Boosted Comms",
                            Point = 4
                        },
                        new
                        {
                            Id = 82,
                            Category = 11,
                            Description = "Your ship gains counter 1.",
                            Name = "Quad Laser Turrets",
                            Point = 5
                        },
                        new
                        {
                            Id = 83,
                            Category = 11,
                            Description = "While performing an anti-squadron attack, you may reroll all red and blue critical icons.",
                            Name = "Point-Defense Reroute",
                            Point = 5
                        },
                        new
                        {
                            Id = 84,
                            Category = 11,
                            Description = "When your ship activates, choose an enemy ship at distance 1–5. If your ship is a larger size class than that ship, it must either discard a navigate token or reduce its speed by 1.",
                            Name = "Phylon Q7 Tractor Beams",
                            Point = 6
                        },
                        new
                        {
                            Id = 85,
                            Category = 11,
                            Description = "During deployment, you may place up to your squadron value in squadrons inside your ship. When you resolve a squadron command, you may deploy those squadrons at distance 1 and activate them.",
                            Name = "Rapid Launch Bays",
                            Point = 6
                        },
                        new
                        {
                            Id = 86,
                            Category = 11,
                            Description = "Medium or large ship only. While overlapping a smaller ship, your ship does not suffer damage from the overlap.",
                            Name = "Hardened Bulkheads",
                            Point = 5
                        },
                        new
                        {
                            Id = 87,
                            Category = 11,
                            Description = "When a friendly non-unique swarm squadron is destroyed, you may discard this card to place that squadron at distance 1 with 1 hull remaining.",
                            Name = "Reserve Hangar Deck",
                            Point = 3
                        },
                        new
                        {
                            Id = 88,
                            Category = 11,
                            Description = "While performing an anti-squadron attack, you may use black dice instead of your anti-squadron armament. You may spend salvo tokens during anti-squadron attacks.",
                            Name = "Flak Guns",
                            Point = 3
                        },
                        new
                        {
                            Id = 89,
                            Category = 11,
                            Description = "Friendly non-heavy squadrons at distance 1–2 prevent enemy squadrons at distance 1 from attacking ships while engaged.",
                            Name = "Advanced Transponder Net",
                            Point = 5
                        },
                        new
                        {
                            Id = 90,
                            Category = 11,
                            Description = "During setup, you may place 2 mine tokens. Ships and squadrons that overlap or move through these tokens suffer damage.",
                            Name = "Proximity Mines",
                            Point = 4
                        },
                        new
                        {
                            Id = 91,
                            Category = 30,
                            Description = "(Lásd az 1. sorszámú kártyát - duplikáció / javított verzió)",
                            Name = "Gunnery Team",
                            Point = 7
                        },
                        new
                        {
                            Id = 92,
                            Category = 30,
                            Description = "While attacking, you may reroll any number of black dice.",
                            Name = "Ordnance Experts",
                            Point = 4
                        },
                        new
                        {
                            Id = 93,
                            Category = 30,
                            Description = "While you resolve a squadron command, your activated squadrons add 1 blue die to their anti-squadron attack pools this round.",
                            Name = "Flight Controllers",
                            Point = 6
                        },
                        new
                        {
                            Id = 94,
                            Category = 30,
                            Description = "While attacking, you may exhaust this card to reroll your entire attack pool.",
                            Name = "Veteran Gunners",
                            Point = 5
                        },
                        new
                        {
                            Id = 95,
                            Category = 30,
                            Description = "While attacking a ship, you may resolve up to two critical effects.",
                            Name = "Fire-Control Team",
                            Point = 2
                        },
                        new
                        {
                            Id = 96,
                            Category = 30,
                            Description = "While attacking, you may exhaust this card and discard 1 die to change another die to an accuracy icon.",
                            Name = "Sensor Team",
                            Point = 5
                        },
                        new
                        {
                            Id = 97,
                            Category = 30,
                            Description = "While attacking a squadron, after the attack steps, you may inflict 1 damage on a friendly squadron engaged with the defender to inflict 1 damage on the defender.",
                            Name = "Ruthless Strategists",
                            Point = 4
                        },
                        new
                        {
                            Id = 98,
                            Category = 30,
                            Description = "During the ship placement phase, you may replace 1 of your defense tokens with a salvo token.",
                            Name = "Local Fire Control",
                            Point = 4
                        },
                        new
                        {
                            Id = 99,
                            Category = 30,
                            Description = "While attacking, you may exhaust this card to reroll any number of dice of a single color.",
                            Name = "Caitken and Shollan",
                            Point = 6
                        },
                        new
                        {
                            Id = 100,
                            Category = 30,
                            Description = "While attacking a ship, you may change 1 blue crit icon to an accuracy icon, OR you may exhaust this card to change 1 accuracy icon to a blue crit icon.",
                            Name = "Weapon Battery Techs",
                            Point = 5
                        },
                        new
                        {
                            Id = 101,
                            Category = 6,
                            Description = "After fleets are deployed, you may place 1 grav well token. Enemy ships deployed at distance 1–3 of this token must begin the game at speed 0.",
                            Name = "G7-X Grav Well Projector",
                            Point = 2
                        },
                        new
                        {
                            Id = 102,
                            Category = 6,
                            Description = "Before an enemy ship at distance 1–5 executes a maneuver, you may exhaust this card to change its speed by 1 for that maneuver.",
                            Name = "G8 Experimental Projector",
                            Point = 8
                        },
                        new
                        {
                            Id = 103,
                            Category = 6,
                            Description = "Before round 1 begins, you may choose and move 1 obstacle up to distance 2.",
                            Name = "Grav Shift Reroute",
                            Point = 2
                        },
                        new
                        {
                            Id = 104,
                            Category = 6,
                            Description = "While a friendly ship at distance 1–3 is defending against an attack from close range, you may exhaust this card to force the attacker to reroll up to 4 attack dice.",
                            Name = "Targeting Scrambler",
                            Point = 5
                        },
                        new
                        {
                            Id = 105,
                            Category = 7,
                            Description = "At the beginning of the Ship Phase, you may spend 1 squadron token. If you do, each friendly squadron at distance 1–5 increases its speed by 1 to its max speed this round.",
                            Name = "All fighters, follow me!",
                            Point = 5
                        },
                        new
                        {
                            Id = 106,
                            Category = 7,
                            Description = "At the beginning of the Ship Phase, you may spend 1 navigate token. If you do, each friendly ship at distance 1–5 may increase or decrease its speed by 1 during its maneuver this round.",
                            Name = "Entrapment Formation!",
                            Point = 5
                        },
                        new
                        {
                            Id = 107,
                            Category = 7,
                            Description = "At the beginning of the Ship Phase, you may spend 1 concentrate fire token. If you do, while attacking a ship at distance 1–5, friendly ships may change 1 die to a hit icon this round.",
                            Name = "Intensify Firepower!",
                            Point = 6
                        },
                        new
                        {
                            Id = 108,
                            Category = 7,
                            Description = "At the beginning of the Ship Phase, you may spend 1 repair token. If you do, during the Status Phase, each friendly ship at distance 1–5 may recover 1 shield.",
                            Name = "Shields to Maximum!",
                            Point = 6
                        },
                        new
                        {
                            Id = 109,
                            Category = 7,
                            Description = "At the beginning of the Ship Phase, you may spend 1 navigate token. If you do, each friendly ship at distance 1–5 gains 1 yaw at its final joint, to a maximum of 2.",
                            Name = "Take Evasive Action!",
                            Point = 6
                        },
                        new
                        {
                            Id = 110,
                            Category = 22,
                            Description = "While you resolve an engineering command, you may increase the number of engineering points available from your dial, then exhaust or discard this card.",
                            Name = "Engineering Team",
                            Point = 5
                        },
                        new
                        {
                            Id = 111,
                            Category = 22,
                            Description = "At the end of the Status Phase, you may exhaust this card to remove 1 facedown damage card from your ship.",
                            Name = "Damage Control Teams",
                            Point = 5
                        },
                        new
                        {
                            Id = 112,
                            Category = 22,
                            Description = "When your ship activates, you may exhaust this card to prevent damage to your crew.",
                            Name = "Medical Team",
                            Point = 1
                        },
                        new
                        {
                            Id = 113,
                            Category = 22,
                            Description = "During the Command Phase or when you activate, you may exhaust this card to give a command token to another friendly ship at distance 1–5.",
                            Name = "Comms Net",
                            Point = 2
                        },
                        new
                        {
                            Id = 114,
                            Category = 22,
                            Description = "While attacking, you may exhaust this card to change 1 black die to a hit icon after rolling black dice.",
                            Name = "Ammunition Experts",
                            Point = 3
                        },
                        new
                        {
                            Id = 115,
                            Category = 22,
                            Description = "During your maneuver or activation, you may exhaust this card to shift 1 shield from one of your hull zones to an adjacent hull zone.",
                            Name = "Auxiliary Shields Team",
                            Point = 3
                        },
                        new
                        {
                            Id = 116,
                            Category = 9,
                            Description = "While a friendly bomber at distance 1–5 attacks a ship, it may reroll 1 attack die.",
                            Name = "Bomber Command Center",
                            Point = 8
                        },
                        new
                        {
                            Id = 117,
                            Category = 22,
                            Description = "(Duplikáció / lásd a 113. sorszámot)",
                            Name = "Comms Net",
                            Point = 2
                        },
                        new
                        {
                            Id = 118,
                            Category = 9,
                            Description = "Friendly and enemy ships and squadrons at distance 1–2 of your ship treat attacks against squadrons as obstructed.",
                            Name = "Jamming Field",
                            Point = 2
                        },
                        new
                        {
                            Id = 119,
                            Category = 9,
                            Description = "When you resolve an engineering command, instead of spending engineering points, you may discard 1 damage card from a friendly ship at distance 1–2 or recover 1 shield on it.",
                            Name = "Repair Crews",
                            Point = 4
                        },
                        new
                        {
                            Id = 120,
                            Category = 9,
                            Description = "After you execute a maneuver, you may exhaust this card to choose an enemy ship at distance 1–3 and change its top command dial to a command of your choice.",
                            Name = "Slicer Tools",
                            Point = 7
                        },
                        new
                        {
                            Id = 121,
                            Category = 9,
                            Description = "When you reveal a command dial, you may discard this card to give up to 5 friendly ships at distance 1–5 1 concentrate fire token.",
                            Name = "Munitions Resupply",
                            Point = 3
                        },
                        new
                        {
                            Id = 122,
                            Category = 9,
                            Description = "When you reveal a command dial, you may discard this card to give up to 5 friendly ships at distance 1–5 1 repair token.",
                            Name = "Parts Resupply",
                            Point = 3
                        },
                        new
                        {
                            Id = 123,
                            Category = 9,
                            Description = "After you execute a maneuver, you may exhaust this card to choose up to a number of friendly squadrons at distance 1–2 equal to your squadron value; those squadrons may each execute a distance 1 move.",
                            Name = "Fighter Coordination Team",
                            Point = 3
                        },
                        new
                        {
                            Id = 124,
                            Category = 20,
                            Description = "Ignition [Close]. While attacking a ship from your ignition arc, each other ship and squadron at distance 1 of the defender suffers 1 damage.",
                            Name = "Orbital Bombardment Particle Cannons",
                            Point = 5
                        },
                        new
                        {
                            Id = 125,
                            Category = 20,
                            Description = "Ignition [Long]. While attacking a ship from your ignition arc, after defense tokens are spent, deal 1 damage to each hull zone (other than the defender's) that the line of sight passes through.",
                            Name = "Superheavy Composite Beam Turbolasers",
                            Point = 7
                        },
                        new
                        {
                            Id = 126,
                            Category = 0,
                            Description = "While your ship is attacking with only its left or right hull zone during its activation, it may add 2 red dice to its attack pool.",
                            Name = "Admiral Ackbar",
                            Point = 38
                        },
                        new
                        {
                            Id = 127,
                            Category = 0,
                            Description = "Before an enemy ship receives a faceup damage card, you may draw 4 damage cards, choose 1 for it to receive, and place the rest on the bottom of the damage deck.",
                            Name = "General Dodonna",
                            Point = 20
                        },
                        new
                        {
                            Id = 128,
                            Category = 0,
                            Description = "When a friendly ship or unique squadron is destroyed, it remains in play and can perform actions as normal until the end of the current round.",
                            Name = "General Rieekan",
                            Point = 30
                        },
                        new
                        {
                            Id = 129,
                            Category = 0,
                            Description = "Friendly ships and squadrons may spend evade tokens at medium range, and may reroll dice with evade tokens at close range.",
                            Name = "Mon Mothma",
                            Point = 27
                        },
                        new
                        {
                            Id = 130,
                            Category = 1,
                            Description = "When a friendly ship is attacking, you may discard 1 shield from any of its hull zones to reroll any number of attack dice.",
                            Name = "Darth Vader (Commander)",
                            Point = 36
                        },
                        new
                        {
                            Id = 131,
                            Category = 1,
                            Description = "After deployment, place 3 facedown command dials on this card. During the Command Phase, you may reveal 1: each friendly ship gains a matching command dial this round.",
                            Name = "Grand Admiral Thrawn",
                            Point = 32
                        },
                        new
                        {
                            Id = 132,
                            Category = 1,
                            Description = "Each friendly ship's hull value is increased by 1 for small ships, 2 for medium ships, and 3 for large ships.",
                            Name = "Admiral Motti",
                            Point = 24
                        },
                        new
                        {
                            Id = 133,
                            Category = 1,
                            Description = "While attacking, each friendly ship may, once per round, discard 1 die to change another die to a face with a crit icon.",
                            Name = "Admiral Screed",
                            Point = 26
                        },
                        new
                        {
                            Id = 134,
                            Category = 2,
                            Description = "While a friendly ship is defending, when it spends a defense token, it reduces the total damage suffered by 1 (once per round).",
                            Name = "Obi-Wan Kenobi",
                            Point = 28
                        },
                        new
                        {
                            Id = 135,
                            Category = 3,
                            Description = "After deployment, choose 3 command tokens. When an enemy ship spends a matching token, deal 1 damage to it.",
                            Name = "Count Dooku",
                            Point = 30
                        },
                        new
                        {
                            Id = 136,
                            Category = 25,
                            Description = "Your ship may perform 1 of its attacks after it executes its maneuver.",
                            Name = "Demolisher (Gladiator-class)",
                            Point = 10
                        },
                        new
                        {
                            Id = 137,
                            Category = 25,
                            Description = "While attacking, the defender cannot spend defense tokens that are already exhausted.",
                            Name = "Avenger (Imperial Star Destroyer)",
                            Point = 5
                        },
                        new
                        {
                            Id = 138,
                            Category = 25,
                            Description = "Your ship's command value is reduced by 1.",
                            Name = "Relentless (Imperial Star Destroyer)",
                            Point = 3
                        },
                        new
                        {
                            Id = 139,
                            Category = 24,
                            Description = "While you resolve a squadron command, activated squadrons that do not move may attack twice.",
                            Name = "Yavaris (Nebulon-B)",
                            Point = 5
                        },
                        new
                        {
                            Id = 140,
                            Category = 24,
                            Description = "While a friendly ship at distance 1–5 is attacking, it may change 1 accuracy icon to a hit icon.",
                            Name = "Home One (MC80 Star Cruiser)",
                            Point = 7
                        },
                        new
                        {
                            Id = 141,
                            Category = 24,
                            Description = "When you resolve a blue crit effect, instead of resolving its normal effect, the defender is dealt 1 faceup damage card.",
                            Name = "Dodonna's Pride (CR90 Corvette)",
                            Point = 6
                        },
                        new
                        {
                            Id = 142,
                            Category = 26,
                            Description = "When a friendly ship at distance 1–5 would suffer damage, you may redirect 1 damage to the Resolute.",
                            Name = "Resolute (Venator-class)",
                            Point = 6
                        },
                        new
                        {
                            Id = 143,
                            Category = 27,
                            Description = "You may deploy extra squadrons during setup and deploy them later in the game.",
                            Name = "Invisible Hand (Providence-class)",
                            Point = 9
                        },
                        new
                        {
                            Id = 144,
                            Category = 31,
                            Description = "While at distance 1 of an enemy ship, you may exhaust this card to exhaust a number of the defender's defense tokens equal to your squadron value.",
                            Name = "Boarding Troopers",
                            Point = 3
                        },
                        new
                        {
                            Id = 145,
                            Category = 31,
                            Description = "While at distance 1 of an enemy ship, you may exhaust this card to flip a number of the defender's facedown damage cards faceup equal to half your engineering value, rounded up.",
                            Name = "Boarding Engineers",
                            Point = 2
                        },
                        new
                        {
                            Id = 146,
                            Category = 31,
                            Description = "While at distance 1 of an enemy ship, you may discard this card to choose and discard an upgrade card (other than a commander) equipped to the defender.",
                            Name = "Darth Vader (Boarding Team)",
                            Point = 3
                        },
                        new
                        {
                            Id = 147,
                            Category = 31,
                            Description = "While at distance 1 of an enemy ship, you may discard this card to deal 2 faceup damage cards to the defender before the attack is resolved.",
                            Name = "Jyn Erso (Boarding Team)",
                            Point = 4
                        },
                        new
                        {
                            Id = 148,
                            Category = 31,
                            Description = "While at distance 1 of an enemy ship, you may discard this card to look at the defender's command dials and change its top dial to a command of your choice.",
                            Name = "Cham Syndulla (Boarding Team)",
                            Point = 5
                        },
                        new
                        {
                            Id = 149,
                            Category = 31,
                            Description = "While at distance 1 of an enemy ship, you may discard this card to choose and discard a weapons team or offensive retrofit upgrade card equipped to the defender.",
                            Name = "Shriv Suurgav (Boarding Team)",
                            Point = 6
                        },
                        new
                        {
                            Id = 150,
                            Category = 0,
                            Description = "While attacking a ship, if a friendly squadron is at distance 1 of the target, you may replace up to 2 attack dice with dice of any color.",
                            Name = "Commander Sato",
                            Point = 32
                        },
                        new
                        {
                            Id = 151,
                            Category = 0,
                            Description = "When you resolve a navigate command (from a dial or token), your ship gains 1 extra yaw at one of its pivot points.",
                            Name = "General Madine",
                            Point = 30
                        },
                        new
                        {
                            Id = 152,
                            Category = 0,
                            Description = "During the Command Phase of rounds 1 and 5, each friendly ship gains command tokens up to its maximum capacity.",
                            Name = "Garm Bel Iblis",
                            Point = 25
                        },
                        new
                        {
                            Id = 153,
                            Category = 0,
                            Description = "During setup, choose a friendly ship and set it aside. Later in the game, at the start of a command phase, it may enter play at distance 1 of another friendly ship.",
                            Name = "Admiral Raddus",
                            Point = 26
                        },
                        new
                        {
                            Id = 154,
                            Category = 1,
                            Description = "At the beginning of the Command Phase, you may assign 1 command token of the same type to each friendly ship in your fleet.",
                            Name = "Grand Moff Tarkin",
                            Point = 38
                        },
                        new
                        {
                            Id = 155,
                            Category = 1,
                            Description = "After deployment, choose 1 defense token type. When an enemy ship spends a token of that type, it must discard it instead of exhausting it unless it spends another token.",
                            Name = "Emperor Palpatine",
                            Point = 35
                        },
                        new
                        {
                            Id = 156,
                            Category = 1,
                            Description = "While friendly squadrons attack ships, they may use accuracy icons to exhaust the defender's defense tokens and deal bonus damage.",
                            Name = "Admiral Sloane",
                            Point = 24
                        },
                        new
                        {
                            Id = 157,
                            Category = 1,
                            Description = "When a friendly ship uses a navigate token to modify its speed, it may increase or decrease its speed by 2 instead of 1 (to a minimum and maximum speed).",
                            Name = "Admiral Ozzel",
                            Point = 20
                        },
                        new
                        {
                            Id = 158,
                            Category = 1,
                            Description = "During your ship's maneuver, it may suffer 1 damage to change its yaw by 1 at the current speed step.",
                            Name = "Moff Jerjerrod",
                            Point = 23
                        },
                        new
                        {
                            Id = 159,
                            Category = 2,
                            Description = "While your ships are defending, defense tokens targeted by accuracy icons can still be resolved, but must be discarded if used.",
                            Name = "Luminara Unduli",
                            Point = 25
                        },
                        new
                        {
                            Id = 160,
                            Category = 2,
                            Description = "At the beginning of the Ship Phase, each friendly ship may spend 1 command token to trigger a special effect regardless of its dial.",
                            Name = "Anakin Skywalker (Commander)",
                            Point = 29
                        },
                        new
                        {
                            Id = 161,
                            Category = 2,
                            Description = "At the beginning of the command phase, you may heal friendly squadrons or grant them escort until the end of the round.",
                            Name = "Plo Koon",
                            Point = 26
                        },
                        new
                        {
                            Id = 162,
                            Category = 3,
                            Description = "While attacking a ship, if the defender's command value is less than yours, you may add 1 red die to your attack pool.",
                            Name = "Mar Tuuk",
                            Point = 28
                        },
                        new
                        {
                            Id = 163,
                            Category = 3,
                            Description = "While attacking, you may reroll 1 die if another friendly ship at distance 1–3 threatens the target.",
                            Name = "Kraken",
                            Point = 26
                        },
                        new
                        {
                            Id = 164,
                            Category = 3,
                            Description = "While attacking, you may add a bonus die of any color for each raid token on the defending ship.",
                            Name = "TF-1726",
                            Point = 26
                        });
                });

            modelBuilder.Entity("ArmadaBackend.Models.Fleet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Fleet");
                });

            modelBuilder.Entity("ArmadaBackend.Models.FleetElement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FleetId")
                        .HasColumnType("int");

                    b.Property<int>("ShipId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FleetId");

                    b.HasIndex("ShipId");

                    b.ToTable("FleetElements");
                });

            modelBuilder.Entity("ArmadaBackend.Models.Ship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Point")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Ships");
                });

            modelBuilder.Entity("ArmadaBackend.Models.ShipCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<int>("ShipId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShipId");

                    b.ToTable("ShipCard");
                });

            modelBuilder.Entity("ArmadaBackend.Models.ShipNameHolder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.PrimitiveCollection<string>("ShipName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ShipNames");
                });

            modelBuilder.Entity("ArmadaBackend.Models.SquadronElement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("FleetId")
                        .HasColumnType("int");

                    b.Property<string>("SquadronName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FleetId");

                    b.ToTable("SquadronElements");
                });

            modelBuilder.Entity("ArmadaBackend.Models.Card", b =>
                {
                    b.HasOne("ArmadaBackend.Models.FleetElement", null)
                        .WithMany("Cards")
                        .HasForeignKey("FleetElementId");
                });

            modelBuilder.Entity("ArmadaBackend.Models.FleetElement", b =>
                {
                    b.HasOne("ArmadaBackend.Models.Fleet", "Fleet")
                        .WithMany("Ships")
                        .HasForeignKey("FleetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArmadaBackend.Models.Ship", "Ship")
                        .WithMany()
                        .HasForeignKey("ShipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fleet");

                    b.Navigation("Ship");
                });

            modelBuilder.Entity("ArmadaBackend.Models.ShipCard", b =>
                {
                    b.HasOne("ArmadaBackend.Models.Ship", "Ship")
                        .WithMany("CardsType")
                        .HasForeignKey("ShipId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ship");
                });

            modelBuilder.Entity("ArmadaBackend.Models.SquadronElement", b =>
                {
                    b.HasOne("ArmadaBackend.Models.Fleet", "Fleet")
                        .WithMany("Squadrons")
                        .HasForeignKey("FleetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fleet");
                });

            modelBuilder.Entity("ArmadaBackend.Models.Fleet", b =>
                {
                    b.Navigation("Ships");

                    b.Navigation("Squadrons");
                });

            modelBuilder.Entity("ArmadaBackend.Models.FleetElement", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("ArmadaBackend.Models.Ship", b =>
                {
                    b.Navigation("CardsType");
                });
#pragma warning restore 612, 618
        }
    }
}
